spring.application.name=automotive-diagnostics

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/garage
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=12345

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=MonSecretJWTTresLongEtSecuriseePourLApplicationAutomotiveDiagnostics2024
jwt.expiration=86400000

# Server Configuration
server.port=8081
